module Workspace.Types exposing (TerminalTab, Workspace)

import Editor.Msg
import FileTree.Model
import FuzzyFinder.Model
import Terminal.Types
import Types exposing (Focused)


{-| A single terminal session within a workspace. `id` is generated by
the Elm side at creation time (workspace-scoped monotonic counter) and
passed to Rust so events can route to the right PTY.
-}
type alias TerminalTab =
    { id : String
    , terminal : Terminal.Types.Model
    , closeArmed : Bool
    }


{-| A single project tab. Every per-project field that used to live on
the top-level Model lives here. The `projectPath` doubles as the
workspace's identity. The terminals list is per-tab — switching project
tabs preserves each one's terminal sessions.

`closeArmed` is the project-tab close-confirmation flag.

-}
type alias Workspace =
    { projectPath : String
    , editor : Maybe Editor.Msg.Model
    , fileHistory : List ( String, String )
    , activeFile : Maybe String
    , terminals : List TerminalTab
    , activeTerminalIndex : Int
    , terminalCounter : Int
    , terminalShowing : Bool
    , fileTree : Maybe FileTree.Model.Model
    , fileTreeShowing : Bool
    , focused : Focused
    , fuzzyFinder : FuzzyFinder.Model.Model
    , closeArmed : Bool
    }
